gui:
  scrollHeight: 8
notARepository: quit
keybinding:
  universal:
    nextTab: l
    prevTab: h
    nextItem-alt: j
    prevItem-alt: k
    scrollUpMain-alt1: u
    scrollDownMain-alt1: d
    focusMainView: "<tab>"
