# remember to make ./local.toml for local changes!

[general]
import = [
    "~/.config/alacritty/themes/themes/rose_pine.toml",
    "~/.config/alacritty/local.toml"
]

[window]
opacity = 0.90

[window.padding]
x = 4

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "Space", mods = "Control", mode = "~Search", action = "ToggleViMode" },
    { key = "H", mods = "Shift", mode = "Vi", action = "First" },
    { key = "L", mods = "Shift", mode = "Vi", action = "Last" },
    { key = "N", mods = "Shift|Control", mode = "~Search", action = "CreateNewWindow" }
]
